# Generated by Django 5.2.15 on 2026-06-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShuttleRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="노선명")),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("mjustation", "명지대역"),
                            ("giheungstation", "기흥역"),
                            ("seoul_campus", "서울캠퍼스"),
                            ("yongin_campus", "용인캠퍼스"),
                        ],
                        max_length=30,
                        verbose_name="출발지",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("mjustation", "명지대역"),
                            ("giheungstation", "기흥역"),
                            ("seoul_campus", "서울캠퍼스"),
                            ("yongin_campus", "용인캠퍼스"),
                        ],
                        max_length=30,
                        verbose_name="도착지",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="노선 설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="운행 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "셔틀 노선",
                "verbose_name_plural": "셔틀 노선 목록",
                "ordering": ["origin", "destination"],
            },
        ),
        migrations.CreateModel(
            name="ShuttleSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.TimeField(verbose_name="출발 시각")),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("weekday", "평일"),
                            ("saturday", "토요일"),
                            ("sunday", "일요일/공휴일"),
                        ],
                        default="weekday",
                        max_length=10,
                        verbose_name="운행 요일 구분",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="운행 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="navigation.shuttleroute",
                        verbose_name="운행 노선",
                    ),
                ),
            ],
            options={
                "verbose_name": "셔틀 시간표",
                "verbose_name_plural": "셔틀 시간표 목록",
                "ordering": ["departure_time"],
                "indexes": [
                    models.Index(
                        fields=["route", "day_type", "is_active"],
                        name="navigation__route_i_685aa5_idx",
                    ),
                    models.Index(
                        fields=["departure_time"], name="navigation__departu_049a6e_idx"
                    ),
                ],
            },
        ),
    ]
