# Generated by Django 5.2.15 on 2026-06-07 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="일정 제목")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                ("description", models.TextField(blank=True, verbose_name="상세 설명")),
                (
                    "campus",
                    models.CharField(
                        choices=[
                            ("seoul", "서울캠퍼스"),
                            ("yongin", "용인캠퍼스"),
                            ("both", "공통"),
                        ],
                        default="both",
                        max_length=10,
                        verbose_name="해당 캠퍼스",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("holiday", "공휴일/휴강"),
                            ("exam", "시험"),
                            ("registration", "수강신청"),
                            ("ceremony", "행사/식"),
                            ("etc", "기타"),
                        ],
                        default="etc",
                        max_length=15,
                        verbose_name="일정 유형",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "학사일정",
                "verbose_name_plural": "학사일정 목록",
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="academic_ac_start_d_989548_idx",
                    ),
                    models.Index(
                        fields=["campus"], name="academic_ac_campus_64ddb5_idx"
                    ),
                ],
            },
        ),
    ]
